### ISSUE TITLE
Merge discourse-sso with sso-discourse?

### ISSUE THREAD

**Issue by wmhilton** [ArmedGuy/discourse_sso_node#6]
Just wondering if the authors have talked to each other. discourse-sso is older (and has a >1.0.0 version, which is significant to those of us adhering to semver) while sso-discourse has a convenient connect-compatible middleware (and a perilously unstable looking version of 0.1.0).

https://www.npmjs.com/package/discourse-sso
https://www.npmjs.com/package/sso-discourse

(I'm just some guy about to integrate Discourse with my Nodejs site.)

**Comment by ArmedGuy** [comment]
No talks have occurred. I released my version when SSO was implemented, and have only updated it if necessary. Writing the middleware is an easy task so I have left this library to be minimalistic.

I also doubt that his version is any less developed than mine, people rarely use semver properly. :D

**Comment by wmhilton** [comment]
Maybe I'll just open an issue asking him to use semver correctly then. ;)
